package day6;

public class Exceptions {

	public static void main(String[] args) {
		/*
		 * 형식:
		 * 	try{
		 * 		예외가 발생될 가능성이 있는 코드
		 * 	}catch(예외클래스1 e)
		 * 		예외 클래스 메시지 출력
		 * 	}
		 * 		:
		 * 	finally{
		 * 		무조건 실행
		 * 		뒤처리
		 * 	}
		 * 
		 * 	함수 안에서 발생할 경우
		 * 	static void method() throws 예외클래스 {
		 * 		함수 안에서 예외가 발생될 경우
		 * 	}
		 * 
		 */
		int array[] = { 1, 2, 3 }; // 크기 3개의 int 배열(이름 : array) 생성(선언 및 할당)
		System.out.println("start"); // "start" 문자열 출력
		try {
			for (int i = 0; i < 4; i++) {
				System.out.println(array[i]);
			}
			
			System.out.println("Process");
		}catch(ArrayIndexOutOfBoundsException e) {
			System.out.println("배열의 범위 초과");
			return;
		}catch (Exception e) {
			e.printStackTrace();
		}finally {
			System.out.println("finally 부분");
		}
		
		System.out.println("end");
		
		method();
	}
	
	static void method() throws IndexOutOfBoundsException {
		int num[] = {1, 2, 3};
		for (int i=0; i<4 ; i++) {
			System.out.println(num[i]);
		}
	}
	
	static void objectCall()throws ClassNotFoundException {
		Class,forName("Myclass")l
	}
}
