package day6;

public class Exceptions {

	public static void main(String[] args) {
		/*
		 * 형식:
		 * 	try{
		 * 		예외가 발생될 가능성이 있는 코드
		 * 	}catch(예외클래스1 e)
		 * 		예외 클래스 메시지 출력
		 * 	}
		 * 		:
		 * 	finally{
		 * 		무조건 실행
		 * 		뒤처리
		 * 	}
		 * 
		 * 	함수 안에서 발생할 경우
		 * 	static void method() throws 예외클래스 {
		 * 		함수 안에서 예외가 발생될 경우
		 * 	}
		 * 
		 */
		int array[] = { 1, 2, 3 }; // 크기 3개의 int 배열(이름 : array) 생성(선언 및 할당)
		System.out.println("start"); // "start" 문자열 출력
		try {
			for (int i = 0; i < 3; i++) { // i가 0부터 3까지 4번 수행
				System.out.println(array[i]); // 배열의 0번부터 3번까지 출력
			}
			
			System.out.println("Process"); // Process 문자열 출력
		}catch(ArrayIndexOutOfBoundsException e) { // 배열 범위초과 예외 발생 시
			System.out.println("배열의 범위 초과"); // 배열의 범위 초과 문자열 출력
			return; // 현재 함수(main) 종료 및 반환(반환 값 없음)
		}catch (Exception e) { // 예외(종류 무관) 발생 시
			e.printStackTrace(); // 해당 에러를 출력한다.
		}finally { // 에러 처리 후 
			System.out.println("finally 부분1");
		}
		
		System.out.println("end");
		
		method();
		
		try {
			objectCall();
		}catch (ClassNotFoundException e ) {
			e.printStackTrace();
		}catch (IndexOutOfBoundsException e) {
			e.printStackTrace();
		}
	}
	
	static void method() throws IndexOutOfBoundsException {
		int num[] = {1, 2, 3};
		for (int i=0; i<4 ; i++) {
			System.out.println(num[i]);
		}
	}
	
	static void objectCall()throws ClassNotFoundException {
		Class.forName("MyClass");
	}
}
